<?php

/*
 * Implementation hook_image_default_styles
 */

function bt_core_image_default_styles(){
  $styles = array();
  
  $styles['bt_questionnaire_image'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 900, 'height' => 600, 'upscale' => 1),
        'weight' => 0
      ),
    )
  );
    
  $styles['bt_questionnaire_image_thumb'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 300, 'height' => 226),
        'weight' => 0
      ),
    )
  );
  return $styles;
}

function bt_core_is_bobbi_user(){
  global $user;
  
  if(user_is_anonymous()){
    return FALSE;
  }
  
  if(bt_core_is_admin()){
    return TRUE;
  }
  
  return in_array('bobbie user', $user->roles);
}

function bt_core_is_admin(){
  global $user; 
  
  if(user_is_anonymous()){
    return FALSE;
  }
  
  return in_array('administrator', $user->roles);
}

function bt_core_menu(){
  $items = array();
  $items['login'] = array(
      'title' => 'Login/Signup',
      'page callback' => 'bt_core_signup',
      'access callback' => 'user_is_anonymous',
      'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

function bt_core_signup(){
  drupal_add_js(drupal_get_path('module', 'bt_core') . '/bt_signup.js');
  $output = '<div id="signup-login-wrapper">';
  $output .= '<div class="signup-login-tabs clearfix">';
  $output .= '<div id="login-tab" class="tab active"><span>' . t('Login') . '</span></div>';
  $output .= '<div id="signup-tab" class="tab"><span>' . t('Signup') . '</span></div>';
  $output .= '</div>';
  $output .= '<div class="signup-login-blocks">';
  $output .= '<div id="login-block" class="block">' . drupal_render(drupal_get_form('user_login')) . '</div>';
  $output .= '<div id="signup-block" class="block hidden">' . drupal_render(drupal_get_form('user_register_form')) . '</div>';
  $output .= '</div>';
  $output .= '</div>';
  
  return $output;
}

function bt_core_user_login(&$edit, $account){
  if (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset') {
    drupal_goto('questionnaire');
  }
}

function bt_core_user_presave(&$edit, $account, $category){
  if($account->uid == 0){
    $role = user_role_load_by_name(('bobbie user'));
    $edit['roles'] = array(
        $role->rid => 'bobbie user'
    );
  }
}

function bt_core_pager($count, $start, $max, $path){
  $out = '<div id="pager">';
  if(($start - $max) >= 0){
    $out .= '<span class="newer"><span class="arrow-w arrow"></span><a href="/' . $path . '?start=' . ($start - $max) . '">Newer</a></span>';
  }
  if($count > ((int)$start + (int)$max)){
    $out .= '<span class="older"><a href="/' . $path . '?start=' . ($start + $max) . '">Older</a><span class="arrow-e arrow"></span></span>';
  }
  $out .= '</div>';
  return $out;
}

function bt_core_get_social_links(){
  $output = '';
  $output .= '<ul class = "social">';
  $output .= '<li><a href = "http://www.facebook.com/sharer.php?s=100&p[title]=What\'s%20Your%20First%20Impression?&p[url]=http://www.bobbie.com/firstimpressions&p[images][0]=http://bobbie.com/wp-content/themes/bobbie-book-2013/img/i_header.jpg" target="_blank" class = "facebook"><img src = "sites/all/themes/zen/zen-internals/images/fb.jpg"></a></li>';
  $output .= '<li><a href = "http://twitter.com/share?text=What\'s%20Your%20First%20Impression?&url=http://www.bobbie.com/firstimpressions" target="_blank" class = "twitter"><img src = "sites/all/themes/zen/zen-internals/images/twitter.jpg"></a></li>';
  $output .= '<li><a href = "mailto:test@test.com?subject=First%20Impressions&amp;body=What%20first%20impression%20do%20I%20make%3F%20Let%20me%20know%20what%20you%20think%2C%20and%20then%20post%20your%20own%20photo%20at%20%3Ca%20href%3D%22Bobbie.com%2FFirstImpressions%22%3EBobbie.com%2FFirstImpression%3C%2Fa%3E!"class = "email"><img src = "sites/all/themes/zen/zen-internals/images/email.jpg"></a></li>';
  $output .= '</ul>';
  $output .= '<span class = "share-text">SHARE THIS PAGE!</span>';
  return $output;
}